export const NoteActions = {
    GET_NOTES_START: "GET_NOTES_START",
    GET_NOTES_SUCCESS: "GET_NOTES_SUCCESS",
    GET_NOTES_ERROR: "GET_NOTES_ERROR",
    CREATE_NOTES_START: "CREATE_NOTES_START",
    CREATE_NOTES_SUCCESS: "CREATE_NOTES_SUCCESS",
    CREATE_NOTES_ERROR: "CREATE_NOTES_ERROR",
}