version: "3.9"
services:
  backend:
    build: ./e2e-backend
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ATLAS_URI: mongodb://admin:password@mongo:27017/
  web:
    build: ./e2e-frontend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      ATLAS_URI: mongodb://mongo:27017/
  mongo:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ~/mongo:/data/db
